CREATE TABLE EMPLOYEE (
    E_ID SERIAL PRIMARY KEY,
    F_NAME VARCHAR(50),
    L_NAME VARCHAR(50),
    Birth_Date DATE,
    SALARY INT,
    E_ROLE VARCHAR(50),
    E_PHOTO VARCHAR(100),
    E_ADDRESS VARCHAR(100),
    E_CITY VARCHAR(50),
    E_COUNTRY VARCHAR(50),
    E_ZIPCODE VARCHAR(50),
    E_USERNAME VARCHAR(50) UNIQUE,
    E_PASSWORD VARCHAR(255),
    E_GENDER VARCHAR(50),
    E_ACTIVE BOOLEAN DEFAULT False
);
CREATE TABLE CUSTOMER (
    C_ID INT PRIMARY KEY,
    C_NAME VARCHAR(50),
    C_ADDRESS VARCHAR(100),
    C_CITY VARCHAR(50),
    C_COUNTRY VARCHAR(50),
    C_ZIPCODE VARCHAR(50),
    C_FAX VARCHAR(50),
    C_PHOTO VARCHAR(100)
);
CREATE TABLE SUPPLIER (
    S_ID INT PRIMARY KEY,
    S_NAME VARCHAR(50),
    S_ADDRESS VARCHAR(100),
    S_CITY VARCHAR(50),
    S_COUNTRY VARCHAR(50),
    S_ZIPCODE VARCHAR(50),
    S_FAX VARCHAR(50),
    S_PHOTO VARCHAR(100)
);
CREATE TABLE STOCK (
    P_ID INT PRIMARY KEY,
    P_NAME VARCHAR(50),
    P_COSTPRICE INT,
    P_SELLPRICE INT,
    P_QUANTITY INT,
    P_PHOTO VARCHAR(100),
    P_DESCRIPTION VARCHAR(100),
    P_CATEGORY VARCHAR(50),
    MODEL_CODE VARCHAR(50),
    EXPIRE_DATE DATE,
    P_STATUS VARCHAR(50)
);
CREATE TABLE SALES (
    SL_ID INT PRIMARY KEY,
    SL_DATE DATE,
    SL_TOTAL INT,
    SL_DISCOUNT INT,
    SL_TAX INT,
    SL_STATUS VARCHAR(50),
    SL_TYPE VARCHAR(50),
    SL_INAMOUNT INT,
    SL_COST INT,
    SL_BILLNUM INT UNIQUE,
    SL_PAYED INT,
    SL_CURRENCY VARCHAR(50),
    C_ID INT,
    FOREIGN KEY (C_ID) REFERENCES CUSTOMER(C_ID)
);
CREATE TABLE PURCHASE (
    PCH_ID INT PRIMARY KEY,
    PCH_DATE DATE,
    PCH_TOTAL INT,
    PCH_TAX INT,
    PCH_COST INT,
    PCH_BILLNUM INT UNIQUE,
    PCH_CURRENCY VARCHAR(50),
    PCH_EXPENSE INT,
    PCH_CUSTOMSCOST INT,
    PCH_CUSTOMSNUM INT,
    S_ID INT,
    FOREIGN KEY (S_ID) REFERENCES SUPPLIER(S_ID)
);

CREATE TABLE DEBTS (
    D_ID INT PRIMARY KEY,
    D_DATE DATE,
    D_TYPE VARCHAR(50),
    D_AMOUNT INT,
    D_CURRENCY VARCHAR(50),
    SL_ID INT,
    FOREIGN KEY (SL_ID) REFERENCES SALES(SL_ID)
);
   
CREATE TABLE SELL_ITEMS (
    P_ID INT,
    SL_ID INT,
    SI_QUANTITY INT,
    SI_TOTAL INT,
    FOREIGN KEY (P_ID) REFERENCES STOCK(P_ID),
    FOREIGN KEY (SL_ID) REFERENCES SALES(SL_ID),
    PRIMARY KEY (P_ID, SL_ID)
);
CREATE TABLE PURCHASE_ITEMS (
    P_ID INT,
    PCH_ID INT,
    PI_QUANTITY INT,
    P_CATEGORY VARCHAR(50),
    PI_TOTAL INT,
    FOREIGN KEY (P_ID) REFERENCES STOCK(P_ID),
    FOREIGN KEY (PCH_ID) REFERENCES PURCHASE(PCH_ID),
    PRIMARY KEY (P_ID, PCH_ID)
);
CREATE TABLE MARKEETING (
    E_ID INT,
    C_ID INT,
    FOREIGN KEY (E_ID) REFERENCES EMPLOYEE(E_ID),
    FOREIGN KEY (C_ID) REFERENCES CUSTOMER(C_ID),
    PRIMARY KEY (E_ID, C_ID)
);

CREATE TABLE REPORT(
    RPT_ID INT PRIMARY KEY,
    RP_TYPE VARCHAR(50) /*thats for the type of the report*/
);

CREATE TABLE PREPARE_REPORT (
    RPT_ID INT,
    E_ID INT,
    C_ID INT,
    P_ID INT,
    FOREIGN KEY (E_ID) REFERENCES EMPLOYEE(E_ID),
    FOREIGN KEY (C_ID) REFERENCES CUSTOMER(C_ID),
    FOREIGN KEY (P_ID) REFERENCES STOCK(P_ID),
    FOREIGN KEY (RPT_ID) REFERENCES REPORT(RPT_ID),
    PRIMARY KEY (RPT_ID,P_ID)
);

 CREATE TABLE REPAIR (
     REP_ID INT PRIMARY KEY,
     REMARKS VARCHAR(100),
     REP_DATE DATE
 );
 CREATE TABLE REPAIR_PROCESS 
 (
     REP_ID INT,
     P_ID INT,
     SP_ID INT,
     SP_QUANTITY INT,
     FOREIGN KEY (REP_ID) REFERENCES REPAIR(REP_ID),
     FOREIGN KEY (P_ID) REFERENCES STOCK(P_ID),
    FOREIGN KEY (SP_ID) REFERENCES STOCK(P_ID),
     PRIMARY KEY (REP_ID,SP_ID)
 );

CREATE TABLE PRICE_QUOTATION (
    PQ_ID INT PRIMARY KEY,
    PQ_DISCOUNT INT,
    PQ_CURRENCY VARCHAR(50),
    PQ_DURATION VARCHAR(50)
);
CREATE TABLE OFFER (
    PQ_ID INT,
    P_ID INT,
    C_ID INT,
    FOREIGN KEY (PQ_ID) REFERENCES PRICE_QUOTATION(PQ_ID),
    FOREIGN KEY (P_ID) REFERENCES STOCK(P_ID),
    FOREIGN KEY (C_ID) REFERENCES CUSTOMER(C_ID),
    PRIMARY KEY (PQ_ID,P_ID)
);

CREATE TABLE NOTIFICATION (
    N_ID INT PRIMARY KEY,
    N_DATE DATE,
    N_TYPE VARCHAR(50),
    N_MESSAGE VARCHAR(100),
    N_STATUS VARCHAR(50)
);
CREATE TABLE NOTIFICATION_EMPLOYEE (
    N_ID INT,
    E_ID INT,
    FOREIGN KEY (N_ID) REFERENCES NOTIFICATION(N_ID),
    FOREIGN KEY (E_ID) REFERENCES EMPLOYEE(E_ID),
    PRIMARY KEY (N_ID,E_ID)
);

INSERT INTO EMPLOYEE (F_NAME, L_NAME, Birth_Date, SALARY, E_ROLE, E_PHOTO, E_ADDRESS, E_CITY, E_COUNTRY, E_ZIPCODE, E_USERNAME, E_PASSWORD, E_GENDER)
VALUES ('Ahmed', 'Fathy', '2004-04-19', 10000, 'Manager', 'ahmed.jpg', 'Giza', 'Giza', 'Egypt', '12345', 'ahmed', '$2b$10$OwzytpGyHBO1XYredXi1Wu2lWJ36oRCPL33S6cimYiYEEkDQcik5e', 'male');
